[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[context.production.environment]
  REACT_APP_API_URL = "https://blindtest-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
